cyoa-step1: cyoa-step1.cpp Page.hpp
	g++ -o cyoa-step1 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step1.cpp
cyoa-step2: cyoa-step2.cpp Story.hpp Page.hpp
	g++ -o cyoa-step2 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step2.cpp
test: test.cpp Story.hpp Page.hpp
	g++ -o test -ggdb3 -Wall -Werror -pedantic -std=gnu++98 test.cpp
cyoa-step3: cyoa-step3.cpp myQueue.hpp Story.hpp Page.hpp
	g++ -o cyoa-step3 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step3.cpp
cyoa-step4: cyoa-step4.cpp Story.hpp Page.hpp
	g++ -o cyoa-step4 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step4.cpp
