cyoa-step1: cyoa-step1.cpp Page.hpp
	g++ -o cyoa-step1 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step1.cpp
cyoa-step2: cyoa-step2.cpp Story.hpp Page.hpp
	g++ -o cyoa-step2 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step2.cpp
